# Generated by Django 6.0.1 on 2026-01-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SnippetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL'), ('bash', 'Bash'), ('other', 'Other')], default='python', max_length=20)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='snippets.snippet')),
            ],
            options={
                'verbose_name': 'Snippet Section',
                'verbose_name_plural': 'Snippet Sections',
                'ordering': ['order'],
            },
        ),
    ]
